name: caller

on:
  pull_request:
    branches: ["main"]

jobs:
  check-for-setup:
      runs-on: ubuntu-22.04
      name: Check if setup was changed??
      steps:
        - uses: actions/checkout@v4
