name: Docker

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  FORCE_COLOR: 3

jobs:
  release_docker:
    name: Build docker images (API, Web)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
