name: Docker

on:
  workflow_run:
    workflows: [caller]
    # branches: ["main"]
    types: [completed]

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  release_docker:
    name: Build docker images (API, Web)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
