name: Docker

on:
  workflow_run:
    workflows: [caller]
    types: [completed]
    # branches: [main]

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  release_docker:
    name: Build docker images (API, Web)
    runs-on: ubuntu-latest
    steps:
      - name: echo
        env:
          BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          echo The name is "$BRANCH" default: "${{ github.event.repository.default_branch }}"
          echo Done
        
